#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias l='ls -lisah'
alias ls='ls -lisah'
alias gtst='git status'
alias git cm='git commit -m'
alias Code='cd ~/Code'

# Folder colors
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
